name: build-and-deploy

on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /opt/hostedtoolcache/deno/
            /home/runner/.cache/deno/
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.33.3"
      - run: deno task publish
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "public/"
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
